-- local OrionLib = loadstring(game:HttpGet(('https://raw.githubusercontent.com/shlexware/Orion/main/source')))()
-- print(("\n"):rep(20))

-- local Window = OrionLib:MakeWindow({Name = "My Cool GUI", HidePremium = true, SaveConfig = false, ConfigFolder = "OrionTest"})

-- --- Locals
-- local username = game.Players.LocalPlayer.Name
-- local boolConvSpeed = false
-- local myFactory = game:GetService("Players").LocalPlayer.PlayerTycoon.Value
-- _G.AutoRPFarmEnabled = false
-- _G.AutoLoopUpgradersEnabled = false
-- --- END Locals

-- local Tab = Window:MakeTab({
--     Name = "Conveyors", 
--     Icon = "rbxassetid://4483345998",
--     PremiumOnly = false
-- })

-- local Section = Tab:AddSection({
--     Name = "Conveyor Speed"
-- })

-- function getDroppedOres()
--     local tbl = {}
--     for i,v in pairs(game:GetService("Workspace").DroppedParts[myFactory.Name]:GetChildren()) do
--         table.insert(tbl, v)
--     end
--     return tbl
-- end

-- function getUpgraders()
--     tbl = {}
--     for i, v in pairs(myFactory:GetChildren()) do
--         if v:FindFirstChild("Model") and v.Model:FindFirstChild("Upgrade") then
--             table.insert(tbl, v)
--         elseif v:FindFirstChild("Model") and v.Model:FindFirstChild("Upgrader") then
--             table.insert(tbl, v)
--         elseif v:FindFirstChild("Model") and v.Model:FindFirstChild("Cannon") then
--             table.insert(tbl, v)
--         end
--     end
--     return tbl
-- end

-- Tab:AddToggle({
-- 	Name = "Enable Conveyor Speed",
-- 	Default = true,
-- 	Callback = function(Value)
-- 		boolConvSpeed = Value
--         if Value then
--             print("Conveyor Speed Enabled")
--         else
--             print("Conveyor Speed Disabled")
--         end
-- 	end
-- })

-- Tab:AddToggle({
--     Name = "Auto RP Farm",
--     Default = false,
--     Callback = function(Value)
--         _G.AutoRPFarmEnabled = Value
--         local player = game.Players.LocalPlayer
--         local tycoonModel

--         if Value then
--             print("Auto RP Farm Enabled")
            
--             for _, model in pairs(game.Workspace.DroppedParts:GetChildren()) do
--                 if model:IsA("Model") then
--                     tycoonModel = model
--                     break
--                 end
--             end

--             print("    Tycoon Model: ", tycoonModel)
--             if tycoonModel then
--                 while _G.AutoRPFarmEnabled do
--                     local furnace
--                     for _, tycoon in pairs(game.Workspace.Tycoons:GetChildren()) do
--                         local ownerModel = tycoon:FindFirstChild("Owner")
--                         if ownerModel and ownerModel.Value == player.Name then
--                             for _, model in pairs(tycoon:GetDescendants()) do
--                                 if model:IsA("Model") then
--                                     local itemId = model:FindFirstChild("ItemId")
--                                     local itemType = model:FindFirstChild("ItemType")
--                                     if itemId and itemId:IsA("IntValue") and itemType and itemType:IsA("IntValue") then
--                                         if itemType.Value == 2 or itemType.Value == 6 then
--                                             local lavaModel = model:FindFirstChild("Model")
--                                             if lavaModel and lavaModel:IsA("Model") then
--                                                 local lavaBrick = lavaModel:FindFirstChild("Lava")
--                                                 if lavaBrick and lavaBrick:IsA("BasePart") then
--                                                     furnace = lavaBrick
--                                                     break
--                                                 end
--                                             end
--                                         end
--                                     end
--                                 end
--                             end
--                         end
--                     end

--                     if furnace then
--                         local parts = tycoonModel:GetChildren()
--                         if #parts > 0 then
--                             for _, part in ipairs(parts) do
--                                 if part:IsA("Part") then
--                                     local furnacePosition = furnace.Position + Vector3.new(0, furnace.Size.Y / 2 + part.Size.Y / 2, 0)
--                                     part.Position = furnacePosition
--                                     wait(0.25)
--                                 end
--                             end
--                         else
--                             print("No parts found in the Factory model, waiting for new parts...")
--                             wait(1)
--                         end
--                     else
--                         print("No lava brick found")
--                         wait(2)
--                     end
--                 end
--             else
--                 print("No Factory model found in the DroppedParts folder")
--             end
--         else
--             print("Auto RP Farm Disabled")
--         end
--     end
-- })

-- Tab:AddButton({
--     Name = "Sell Ores",
--     Callback = function()
--         for i, v in pairs(getDroppedOres()) do
--             if myFactory:FindFirstChild("Frozen Justice") then
--                 firetouchinterest(v, myFactory["Basic Furnace"].Model.Lava, 0)
--                 task.wait()
--                 firetouchinterest(v, myFactory["Basic Furnace"].Model.Lava, 1)
--             end
--         end
--     end
-- })

-- Tab:AddToggle({
--     Name = "Auto Loop Upgraders",
--     default = false,
--     Callback = function(Value)
--         if Value then
--             _G.AutoLoopUpgradersEnabled = true
--             print("Auto Loop Upgraders Enabled")
            
--             while _G.AutoLoopUpgradersEnabled do
--                 for i, v2 in pairs(getDroppedOres()) do
--                     for i2, v in pairs(getUpgraders()) do
--                         print(v)
--                         if v.Model:FindFirstChild("Upgrade") then
--                             firetouchinterest(v2,v.Model.Upgrade,0)
--                             task.wait()
--                             firetouchinterest(v2,v.Model.Upgrade,1)
--                         elseif v.Model:FindFirstChild("Upgrader") then
--                             firetouchinterest(v2,v.Model.Upgrader,0)
--                             task.wait()
--                             firetouchinterest(v2,v.Model.Upgrader,1)
--                         elseif v.Model:FindFirstChild("Cannon") then
--                             firetouchinterest(v2,v.Model.Cannon,0)
--                             task.wait()
--                             firetouchinterest(v2,v.Model.Cannon,1)
--                         end
--                     end
--                 end
--             end
--         else
--             print("Auto Loop Upgraders Disabled")
--         end
--     end
-- })

-- Tab:AddBind({
--     Name = "Close GUI",
--     Default = Enum.KeyCode.K,
--     Hold = false,
--     Callback = function()
--         OrionLib:Destroy()
--     end    
-- })

-- OrionLib:Init()
